### ISSUE TITLE
Can't Find Package grvc_quadrotor_gazebo

### ISSUE THREAD

**Issue by Si-lhouette** [margaridaCF/FlyingOctomap#1]
Hi,
in 'octree_and_gazebo_grvc_velodyne.launch' :
<include file="$(find grvc_quadrotor_gazebo)/launch/spawn_quad_velodyne.launch">

BUT there is no such package, I found the package on 'https://github.com/fbalaban/grvcQuadrotor.git'. BUT it still not contain spawn_quad_velodyne.launch.

I wonder where to find it.

**Comment by margaridaCF** [comment]
Hi!

Great to know the code is of use to you!

I recommend using [FlyingOctomap_code repository, tag 2019-09-04_1442_nearesNeighbour](https://github.com/margaridaCF/FlyingOctomap_code/tree/2019-09-04_1442_nearesNeighbour)
And kindly pose your questions on that repository.

Best regards
